# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_xss')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_xss')
    _xss = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_xss', [dirname(__file__)])
        except ImportError:
            import _xss
            return _xss
        try:
            _mod = imp.load_module('_xss', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _xss = swig_import_helper()
    del swig_import_helper
else:
    import _xss
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class XScreenSaverInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, XScreenSaverInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, XScreenSaverInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["window"] = _xss.XScreenSaverInfo_window_set
    __swig_getmethods__["window"] = _xss.XScreenSaverInfo_window_get
    if _newclass:
        window = _swig_property(_xss.XScreenSaverInfo_window_get, _xss.XScreenSaverInfo_window_set)
    __swig_setmethods__["state"] = _xss.XScreenSaverInfo_state_set
    __swig_getmethods__["state"] = _xss.XScreenSaverInfo_state_get
    if _newclass:
        state = _swig_property(_xss.XScreenSaverInfo_state_get, _xss.XScreenSaverInfo_state_set)
    __swig_setmethods__["kind"] = _xss.XScreenSaverInfo_kind_set
    __swig_getmethods__["kind"] = _xss.XScreenSaverInfo_kind_get
    if _newclass:
        kind = _swig_property(_xss.XScreenSaverInfo_kind_get, _xss.XScreenSaverInfo_kind_set)
    __swig_setmethods__["til_or_since"] = _xss.XScreenSaverInfo_til_or_since_set
    __swig_getmethods__["til_or_since"] = _xss.XScreenSaverInfo_til_or_since_get
    if _newclass:
        til_or_since = _swig_property(_xss.XScreenSaverInfo_til_or_since_get, _xss.XScreenSaverInfo_til_or_since_set)
    __swig_setmethods__["idle"] = _xss.XScreenSaverInfo_idle_set
    __swig_getmethods__["idle"] = _xss.XScreenSaverInfo_idle_get
    if _newclass:
        idle = _swig_property(_xss.XScreenSaverInfo_idle_get, _xss.XScreenSaverInfo_idle_set)
    __swig_setmethods__["eventMask"] = _xss.XScreenSaverInfo_eventMask_set
    __swig_getmethods__["eventMask"] = _xss.XScreenSaverInfo_eventMask_get
    if _newclass:
        eventMask = _swig_property(_xss.XScreenSaverInfo_eventMask_get, _xss.XScreenSaverInfo_eventMask_set)

    def __init__(self):
        this = _xss.new_XScreenSaverInfo()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _xss.delete_XScreenSaverInfo
    __del__ = lambda self: None
XScreenSaverInfo_swigregister = _xss.XScreenSaverInfo_swigregister
XScreenSaverInfo_swigregister(XScreenSaverInfo)

ScreenSaverOff = _xss.ScreenSaverOff
ScreenSaverOn = _xss.ScreenSaverOn
ScreenSaverCycle = _xss.ScreenSaverCycle
ScreenSaverDisabled = _xss.ScreenSaverDisabled
ScreenSaverBlanked = _xss.ScreenSaverBlanked
ScreenSaverInternal = _xss.ScreenSaverInternal
ScreenSaverExternal = _xss.ScreenSaverExternal

def get_info():
    return _xss.get_info()
get_info = _xss.get_info
# This file is compatible with both classic and new-style classes.

cvar = _xss.cvar

